TubikDash/TubikDash/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from TubikDash import views
from django.contrib.auth import views as login_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("about/", include("about.urls", namespace="about")),
    path("main/", include("homepage.urls", namespace="homepage")),
    path("dashes/", include("dashes.urls")),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
    path('accounts/login/', login_view.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path('accounts/logout/', login_view.LogoutView.as_view(next_page="/"), name="logout"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path("", views.redirect_to_homepage),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path("__debug__/", include(debug_toolbar.urls)),] + urlpatterns

TubikDash/about/urls.py
from django.contrib.auth import views
from django.urls import path

from about import views

app_name = "about"

urlpatterns = [
    path("", views.main_page, name="main_page")
]

TubikDash/accounts/urls.py
from django.contrib.auth import views
from django.urls import path

import accounts.forms
import accounts.views

app_name = "accounts"

urlpatterns = [
    path('register/', accounts.views.register, name='register'),
]

TubikDash/dashes/urls.py
from dashes import views
from django.urls import path
from dashes import stocks
from dashes.views import dash_demo_one, exchange_info, main

app_name = "dashes"

urlpatterns = [
    path("stocks/", dash_demo_one, name="dash_demo_one"),
    path("exchange_info/", exchange_info, name="exchange_info"),
    path("", main, name="dash_main"),
]

TubikDash/homepage/urls.py
from django.urls import path
from . import views

app_name = "homepage"

urlpatterns = [
    path("", views.main, name="main"),
]

TubikDash/about/models.py
from django.db import models

# Create your models here.

TubikDash/accounts/models.py
import sys

import django.contrib.auth.models
from django.db import models
from django.utils.translation import pgettext_lazy


__all__ = ("User",)


class UserManager(django.contrib.auth.models.UserManager):
    def get_queryset(self):
        return super().get_queryset().select_related("account")


class Account(models.Model):
    user = models.OneToOneField(
        django.contrib.auth.models.User,
        related_name="account",
        on_delete=models.CASCADE,
    )

    parameter = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.user.username


class User(django.contrib.auth.models.User):
    class Meta:
        proxy = True

    def add_notification(self, title, content):
        Notification.objects.create(
            user=self,
            title=title,
            content=content,
        )

    objects = UserManager()

TubikDash/dashes/models.py
from django.db import models

# Create your models here.

TubikDash/homepage/models.py
# Импорт модуля models из библиотеки Django
from django.db import models
# Определение класса MyModel, который наследует модель Django Model
class MyModel(models.Model):
    # Определение поля id типа AutoField как первичного ключа
    id = models.AutoField(primary_key=True)
    # Определение поля phone типа CharField с максимальной длиной в 20 символов
    phone = models.CharField(max_length=20)

    # Определение метода __str__, который будет использоваться для представления экземпляров модели в виде строки
    def __str__(self):
        return self.phone

TubikDash/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

TubikDash/TubikDash/views.py
from django.shortcuts import redirect


def redirect_to_homepage(request):
    return redirect("homepage:main")

TubikDash/about/views.py
from django.shortcuts import render


def main_page(request):
    return render(request, "about/about.html")

TubikDash/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegisterForm


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Создан аккаунт {username}!')
            return redirect('about:main_page')
    else:
        form = UserRegisterForm()
    return render(request, 'accounts/register.html', {'form': form})

TubikDash/dashes/views.py
from django.shortcuts import render

# Create your views here.
import matplotlib.pyplot as plt
from io import BytesIO
import base64
from django.http import HttpResponse
from .currency_exchange_rate import hui


def dash_demo_one(request):
    return render(request, "dashes/dash1.html")


def exchange_info(request):
    n = []
    result = hui()
    for i in result:
        element1, element2 = result[i]["Name"], result[i]["VunitRate"]
        n.append([element1, element2])
    context_dict = {"n": n}
    return render(request, "dashes/exchange_info.html", context=context_dict)


def main(request):
    return render(request, "dashes/catalog.html")

TubikDash/homepage/views.py
from django.shortcuts import render


def main(requset):
    return render(requset, "homepage/homepage.html")

TubikDash/templates/about/about.html
{% extends "base.html" %}
{% block content %}
	{% load static %}
	<body data-spy="scroll" data-target=".navbar-collapse">
	<!--[if lt IE 8]>
	<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a
		href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
	<![endif]-->
	<section id="lessons" class="lessons">
		<div class="container">
			<div class="row">
				<div class="main_lessons">
					<div class="col-sm-8 col-sm-offset-1">
						<div class="main_lessons_area sections">
							<div class="lesson_title"><br><br><br><br><br>
								<h1>НАШ СЕРВИС</h1>
								<p>УДОБЕН</p>
							</div>
							<div class="lesson_content">
								<ul class="lessonsborder">
									<li><i class="fa fa-clone"></i> <a href="">ИЗУЧАЙ</a></li>
									<li><i class="fa fa-globe"></i> <a href="">АНАЛИЗИРУЙ</a></li>
									<li><i class="lnr lnr-rocket"></i> <a href="">ПРЕДУГАДЫВАЙ</a></li>
									<li><i class="lnr lnr-volume-high"></i> <a href="">ЗАРАБАТЫВАЙ</a></li>

								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>


	<section id="portfolio" class="portfolio">
		<div class="container">
			<div class="row">
				<div class="main_portfolio sections">
					<div class="head_title text-center">
						<h2>НАШ ПРОЕКТ</h2>
						<div class="separator"></div>
						<p>Разработка предназначена для банков, которым нкобходим сервис для быстрого и удобного анализа и отслеживания данных курсов, акций, параметров</p>
					</div>
				</div>
			</div>
		</div>
		<div class="modal-footer">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
				aria-hidden="true">&times;</span></button>
		</div>
		<section id="callus" class="callus">
			<div class="callus_overlay">
				<div class="container">
					<div class="row">
						<div class="main_callus">
							<div class="col-sm-6 col-xs-12">
								<div class="single_callus">
									<div class="skypeicon_left">
										<i class="fa fa-envelope"></i>
										<h2>НАПИШИТЕ НАМ!</h2>
										<h3>И ПОЛУЧИ ПОДДЕРЖКУ</h3>
										<div class="skypeicon_right">
											<h3>mishabor7@mail.ru</h3>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>


		<section id="testimonial" class="testimonial">
			<div class="container">
				<div class="row">
					<div class="main_testimonial_area sections text-center">
						<div class="head_title">
							<h2>НАША КОМАНДА</h2>
							<div class="separator"></div>
						</div>
						<div class="main_testimonial_content">
							<div class="single_testimonial">
								<div class="single_test_thumbnail">
									<img class="img-circle img-responsive" src="{% static "img/misha.jpg" %}"
									     alt=""/>
								</div>
								<div class="single_test_content">
									<p>Гений, эстет, бог, или просто - нэхадерет</p>
									<div class="single_author_content">
										<h2>Миша Борисов</h2>
										<p>Разработчик</p>
									</div>
								</div>
							</div>
							<div class="single_testimonial">
								<div class="single_test_thumbnail">
									<img class="img-circle img-responsive" src="{% static "img/aur.jpg" %}" alt=""/>
								</div>
								<div class="single_test_content">
									<p>Бизнесмен, филантроп, на обложке плей-бой</p>

									<div class="single_author_content">
										<h2>Аюр Ихласов</h2>
										<p>Разработчик</p>
									</div>
								</div>
							</div>

						</div>
					</div>
				</div>
			</div>
		</section>

	</body>
{% endblock %}

TubikDash/templates/accounts/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Вход</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Войти</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Нужен аккаунт? <a class="ml-2" href="{% url 'accounts:register' %}">Регистрация</a>
            </small>
        </div>
    </div>
{% endblock content %}

TubikDash/templates/accounts/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Добро пожаловать в клуб Python Bytes</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Регистрация</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Уже есть аккаунт? <a class="ml-2" href="{% url "login" %}">Вход</a>
            </small>
        </div>
    </div>
{% endblock content %}

TubikDash/templates/base.html
{% load static %}
<!doctype html>
<!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang=""> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>Guiter School Education html Template</title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="apple-touch-icon" href="apple-touch-icon.png">
	<link rel="stylesheet" href="{% static "css/navmenu/styles.css" %}">
	<link rel="stylesheet" href="{% static "css/portfolio.jquery.css" %}">
	<link rel="stylesheet" href="{% static "css/fonticons.css" %}">
	<link rel="stylesheet" href="{% static "style.css" %}">
	<link rel="stylesheet" href="{% static "fonts/stylesheet.css" %}">
	<link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}">
	<link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
	<link rel="stylesheet" href="{% static "css/plugins.css" %}"/>
	<link rel="stylesheet" href="{% static "css/style.css" %}">
	<link rel="stylesheet" href="{% static "css/responsive.css" %}"/>
	<script src="{% static "js/vendor/modernizr-2.8.3-respond-1.4.2.min.js" %}"></script>
</head>
	{% include "includes/header.html" %}
<div style="min-height: 100vh;
            flex-grow: 1;">
	{% if messages %}
		{% for message in messages %}
			<div class="alert alert-{{ message.tags }}">
				{{ message }}
			</div>
		{% endfor %}
	{% endif %}
	{% block content %}
	{% endblock content %}
</div>
<footer id="footer">
	{% include "includes/footer.html" %}
</footer>
</html>

TubikDash/templates/dashes/catalog.html
{% extends "base.html" %}

{% block content %}
	{% load static %}
CATALOG
	<img src="https://amg-cement.ru/wp-content/uploads/3/8/9/389248473de6fabdb86b3d99a2624067.jpeg">
	<img src="https://eurasianeconomic.org/files/2642/poison.jpg">
	<img src="https://avatars.mds.yandex.net/i?id=89f6ba24aebaa345e616e8a850d407279b4605e9-9289605-images-thumbs&n=13">
{% endblock %}

TubikDash/templates/dashes/dash1.html
{% extends "base.html" %}

{% block content %}
	{% load static %}
	{% load plotly_dash %}
	{% plotly_app name="Simple_example" %}
{% endblock %}

TubikDash/templates/graph_template.html
<!DOCTYPE html>
<html>
<head>
    <title>График</title>
</head>
<body>
    <img src="{% url 'plot_graph' %}" />
</body>
</html>

TubikDash/templates/homepage/homepage.html
{% extends "base.html" %}

{% block content %}
	{% load static %}
	<body data-spy="scroll" data-target=".navbar-collapse">
	<!--[if lt IE 8]>
	<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a
		href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
	<![endif]-->

	<!--Home page style-->


	<section id="home" class="home text-right">
		<div class="overlay">
			<div class="container">
				<div class="row">
					<div class="col-sm-8 col-sm-offset-4">
						<div class="main_home_content">
							<div class="single_home">
								<div class="main_home wow fadeInUp" data-wow-duration="700ms">
									<h1>УДОБНЫЕ ДАШБОРДЫ</h1>
									<h1 class="subtitle">ДЛЯ КАЖДОГО</h1>
								</div>
							</div>
							<div class="single_home">
								<div class="main_home wow fadeInUp" data-wow-duration="700ms">
									<h1>УДОБНЫЕ ДАШБОРДЫ</h1>
									<h1 class="subtitle">ДЛЯ КАЖДОГО</h1>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>


	<section id="service" class="service">
		<div class="container">
			<div class="row">
				<a href="#lessons" class="service_border_raund text-center">
					<img src="{% static "img/downicon.png" %}" alt=""/>
				</a>
				<div class="main_service_area sections text-center">
					<div class="head_title text-center">
						<h2>СЕРВИСЫ</h2>
						<div class="separator"></div>
						<p>Наш сервис предлагает для вас множество услуг, основными из них являются:</p>
					</div>
					<div class="col-sm-4">
						<div class="single_service">
							<div class="single_service_icon">
								<i class="lnr lnr-chart-bars"></i>
							</div>

							<h3>ТЕКУЩИЕ КУРСЫ</h3>
							<div class="separator"></div>
						</div>
					</div>
					<div class="col-sm-4">
						<div class="single_service">
							<div class="single_service_icon">
								<i class="lnr lnr-magic-wand"></i>
							</div>

							<h3>ПРЕДСКАЗАНИЕ КУРСОВ</h3>
							<div class="separator"></div>
						</div>
					</div>
					<div class="col-sm-4">
						<div class="single_service">
							<div class="single_service_icon">
								<i class="lnr lnr-pie-chart"></i>
							</div>

							<h3>АНАЛИТИКА</h3>
							<div class="separator"></div>
						</div>
					</div>

				</div>
			</div>
			<a href="{% url "dashes:dash_main" %}">
				<button type="submit" class="btn-info"
				        style="display: block; margin-right: auto; margin-left: auto; border: none; height: 100px; width: 300px; border-radius: 30px; margin-top: -60px; margin-bottom: 40px">
					НАЧАТЬ
				</button>
			</a>
		</div>
	</section>


	<div class="scrollup">
		<a href="#"><i class="fa fa-chevron-up"></i></a>
	</div>
	<script src="{% static "js/vendor/jquery-1.11.2.min.js" %}"></script>
	<script src="{% static "js/vendor/bootstrap.min.js" %}"></script>
	<script src="{% static "js/jquery.easypiechart.min.js" %}"></script>
	<script src="{% static "js/portfolio.jquery.js" %}"></script>
	<script src="{% static "js/jquery.mixitup.min.js" %}"></script>
	<script src="{% static "js/jquery.easing.1.3.js" %}"></script>
	<script src="{% static "js/jquery.slicknav.min.js" %}"></script>
	<script src="{% static "js/plugins.js" %}"></script>
	<script src="{% static "js/main.js" %}"></script>

	</body>
{% endblock %}

TubikDash/templates/includes/footer.html
{% load static %}
<footer id="footer" class="footer">
	<section id="footer_widget" class="footer_widget">
		<div class="container">
			<div class="row">
				<div class="main_widget">


					<div class="row">
						<div class="col-sm-4">
							<div class="single_widget wow fadeIn" data-wow-duration="800ms">
								<div class="footer_logo">
									<img src="{% static "img/logo2.png" %}" alt=""/>
								</div>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut in egestas lectus.
									Etiam tempor odio tellus, at bibendum neque faucibus quis. Sed vel facilisis
									elit. </p>
								<p>Nullam fringilla pharetra diam non accumsan. Morbi eget aliquam mauris.
									Etiam vehicula efficitur mi.</p>
							</div>
						</div>
						<div class="col-sm-4">
							<div class="single_widget wow fadeIn" data-wow-duration="800ms">
								<h4 class="footer_title">CONTACT</h4>
								<div class="separator3"></div>
								<ul>
									<li><a href=""><i class="fa fa-envelope"></i> info@guitarlessons.com</a></li>
									<li><a href=""><i class="fa fa-phone"></i> 0123 456 789 0112</a></li>
									<li><a href=""><i class="fa fa-map-marker"></i> Greenplatz Ben 29, Germany 60435</a>
									</li>
									<li><a href=""><i class="fa fa-fax"></i> (0012) 654 356 445</a></li>
								</ul>
							</div>
						</div>
						<div class="col-sm-4">
							<div class="single_widget wow fadeIn" data-wow-duration="800ms">
								<h4 class="footer_title">LATEST NEWS</h4>
								<div class="separator3"></div>
								<ul>
									<li class="single_latest_news">
										<p class="latest_date">02.08.2015</p>
										<p class="subtitle">Etiam tempor odio tellus.</p>
										<p class="details">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut
											in egestas lectus. Etiam tempor odio tellus.</p>
									</li>

									<li class="single_latest_news">
										<p class="latest_date">02.08.2015</p>
										<p class="subtitle">Etiam tempor odio tellus.</p>
										<p class="details">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut
											in egestas lectus. Etiam tempor odio tellus.</p>
									</li>

								</ul>
							</div>
						</div>
					</div>


				</div>
			</div>
		</div>
	</section>
	<div class="scrollup">
		<a href="#"><i class="fa fa-chevron-up"></i></a>
	</div>
	<div class="container">
		<div class="row">

			<div class="col-md-12 col-sm-12">
				<div class="copyright_text text-center">
					<p class=" wow fadeInRight" data-wow-duration="1s">Made with <i class="fa fa-heart"></i> by <b>Tubik
						team</b>
						2024</p>
				</div>
			</div>
		</div>
	</div>
	<script src="{% static "js/vendor/jquery-1.11.2.min.js" %}"></script>
	<script src="{% static "js/vendor/bootstrap.min.js" %}"></script>
	<script src="{% static "js/jquery.easypiechart.min.js" %}"></script>
	<script src="{% static "js/portfolio.jquery.js" %}"></script>
	<script src="{% static "js/jquery.mixitup.min.js" %}"></script>
	<script src="{% static "js/jquery.easing.1.3.js" %}"></script>
	<script src="{% static "js/jquery.slicknav.min.js" %}"></script>
	<script src="{% static "js/plugins.js" %}"></script>
	<script src="{% static "js/main.js" %}"></script>

</footer>

TubikDash/templates/includes/form.html
{% for field in form %}
    <div class="form-group mb-3">
        <label for="{{ field.auto_id }}" class="form-label">{{ field.label }}</label>
        {{ field }}
        {% if field.errors %}
            {% for error in field.errors %}<div class="invalid-feedback">{{ error|safe }}</div>{% endfor %}
        {% endif %}
        {% if field.help_text %}
            <div class="form-text text-muted">
                <p>{{ field.help_text|safe }}</p>
            </div>
        {% endif %}
    </div>
{% endfor %}
{% if form.non_field_errors %}
    <div class="alert alert-danger">
        {% for error in form.non_field_errors %}{{ error|safe }}{% endfor %}
    </div>
{% endif %}

TubikDash/templates/includes/header.html
{% load static %}
<nav>
	<div class="container">
		<div class="nav-top clearfix">
			<div class="logo">
				<a href="" class="navbar-brand"><img src="{% static "img/logo.png" %}" alt="Logo"/></a>
			</div>
			<button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse" type="button">
				<span class="sr-only">Toggle navigation</span><i class="fa fa-bars"></i>
			</button>

		</div>
	</div>

	<div class="main-nav navbar-collapse collapse">
		<div class="container">
			<div class="minilogo">
				<a href="" class="navbar-brand"><img src="{% static "img/logo2.png" %}" alt="Logo"/></a>
			</div>
			<ul class="nav nav-justified">
				<li><a href="{% url "homepage:main" %}">Главная</a></li>
					<li><a href="{% url "about:main_page" %}">О нас</a></li>
				<li><a href="{% url "dashes:dash_main" %}">Дашборды</a></li>
			</ul>
		</div>
	</div>
</nav>